### ISSUE TITLE
A way to resolve values for a similarly named entry from more than 1 provider

### ISSUE THREAD

**Issue by kevbook** [tellerops/teller#118]
## Feature Request
A way to resolve values for a similarly named entry from more than 1 provider

**Comment by kaplanelad** [comment]
Hey @kevbook can you please elaborate this case?
Example usecase will be perfect

**Comment by kevbook** [comment]
Absolutely. A common use case:
1. Our dev creds for service X lives on AWS secrets manager 
2. As engineers are working locally, they tend to override certain env vars 

```bash
aws_secretsmanager:
    env:
      # Values http,library-a
      DEBUG_LOGGER:
        path: dev/service-x

dotenv:
    env:
      # Values http,library-a,library-b,library-c
      DEBUG_LOGGER:
        path: .local.env
```

A key can be in 2 vaults, there is no way to set precedence when using `teller show|sh|json|yaml`

**Comment by kaplanelad** [comment]
@kevbook, any thoughts about my previous message?

**Comment by kaplanelad** [comment]
As it's been quite some time since I've received any response to this pull request, I'll be closing it for now. Thank you for your consideration and time.

If anyone would like to continue the discussion on this issue, please feel free to reopen the ticket.
