### ISSUE TITLE
Pass Provider

### ISSUE THREAD

**Issue by marcofranssen** [tellerops/teller#127]
## Details
- Name: Pass
- URL: https://www.passwordstore.org/
- Modes: read+write
- GitHub projects: N.A.
- API Documentation: https://www.passwordstore.org/

An example of a project that does have Pass integration is https://github.com/99designs/aws-vault

You can find their Pass implementation here.

https://github.com/99designs/keyring

**Comment by kaplanelad** [comment]
Hey @marcofranssen this for provider suggestion
Do you want to create a pull request with the new provider? I can assist you if you need to

**Comment by marcofranssen** [comment]
If no one else picks it up, over time if I find some spare moments I can try to give it a shot.

**Comment by kaplanelad** [comment]
Cool, so the first volunteer will write a message here to prevent duplicate work.

**Comment by ceekay47** [comment]
Hi @kaplanelad, I would like to work on this. Can you please assign this to me and help me get started? Thanks!

**Comment by kaplanelad** [comment]
Hey @marcofranssen, 
You can follow this [guide](https://github.com/tellerops/teller/blob/master/doc/new-provider.md) to initialize a new provider in Teller.

If you have any follow-up questions feel free to write them here, or we can jump to a short live session if you need to

**Comment by MrLuje** [comment]
@kaplanelad 
Hi, if nobody started yet, I'd like to give it a shot

**Comment by MrLuje** [comment]
After having a look, Teller already supports gopass (https://github.com/tellerops/teller/blob/master/pkg/providers/gopass.go) which states to be `100% API-compatible to pass` so I don't think we need a dedicated Pass implementation
