### ISSUE TITLE
Windows Credentials Manager Provider

### ISSUE THREAD

**Issue by marcofranssen** [tellerops/teller#128]
## Details
- Name: Windows Credentials Manager
- URL: https://support.microsoft.com/en-au/help/4026814/windows-accessing-credential-manager
- Modes: read+write
- GitHub projects: N.A.
- API Documentation: https://support.microsoft.com/en-au/help/4026814/windows-accessing-credential-manager

An example of a project that does have `Windows Credentials Manager` integration is https://github.com/99designs/aws-vault

You can find their `Windows Credentials Manager` implementation here.

https://github.com/99designs/keyring

**Comment by kaplanelad** [comment]
Hey @marcofranssen this for provider suggestion
Do you want to create a pull request with the new provider? I can assist you if you need to

**Comment by marcofranssen** [comment]
I don't have a Windows machine, but I figured if we want to adopt this tool in our team this would probably be required for some folks.

**Comment by kaplanelad** [comment]
I'll be closing this pull request for the time being.
