### ISSUE TITLE
Provider Request - Passbolt

### ISSUE THREAD

**Issue by Jagostini** [tellerops/teller#130]
## Details
- Name: passbolt
- URL: https://www.passbolt.com/
- Modes: (read/write/read+write)
- GitHub projects: https://github.com/passbolt/passbolt_api
- API Documentation: https://help.passbolt.com/api

**Comment by kaplanelad** [comment]
Hey @Jagostini 
we're accepting PRs,
Do you want to implement this provider? I can assist you if you need to

**Comment by Tanmoy741127** [comment]
Hey I am inetersred in implementing Passbolt in teller.
 @kaplanelad  Can you please assign this issue?

**Comment by kaplanelad** [comment]
Sure @Tanmoy741127, 
Check out [this doc](https://github.com/tellerops/teller/blob/master/doc/new-provider.md) for adding new provider doc.

Let me know if you need some help

**Comment by Tanmoy741127** [comment]
Thanks

**Comment by Tanmoy741127** [comment]
@kaplanelad in teller, is there any built in support for GPG authentication ?

**Comment by kaplanelad** [comment]
No, In teller there is no provider authentication mechanism. 
The idea behind that is to give the provider the auth ownership and not manage it in teller for each provider.

Do you want to share why do you needs it?

**Comment by Tanmoy741127** [comment]
I was going through the documentation of passboult. They need GPG key based
authentication,  for that I was looking if teller has used it for any other
integration.
No problem, I will add the GPG authentication mechanism for this

**Comment by kaplanelad** [comment]
I think we need to keep out this logic outside Teller. 
My thoughts:
1. can we get the file path in the environment variable and send it to the provider?
2. We can add to the provider doc a pre-requisite step for using this provider? and let the user doing this logic?

**Comment by Tanmoy741127** [comment]
We should take the path of key from the user.

**Comment by kaplanelad** [comment]
I'll be closing this pull request for the time being.
