### ISSUE TITLE
Shell export not working when password has special characters

### ISSUE THREAD

**Issue by kpetremann** [tellerops/teller#131]
## Expected Behavior
The password when executing `teller sh` should be enclosed in quote to avoid interpreting special characters such as parentheses.

## Current Behavior
Currently passwords are not escaped, resulting in the following error:
```bash: syntax error near unexpected token '('```

## Possible Solution
Enclose password with quote and substitute single quote already in the variable
`strings.ReplaceAll(v.Value, "'", "'\"'\"'")`

I've a commit ready to be submitted as a PR: https://github.com/kpetremann/teller/commit/761009133fdb3a445703e0a3344276e78ab6f881

## Steps to Reproduce
1. have this kind of secret: `()"';@  \(\)\"\'\;\@`
2. `eval "$(teller sh)"`

## Context
Secrets can have special characters which should not be interpreted by the shell

## Specifications
  - Version: 1.5.3
  - Platform: Ubuntu 22.04

**Comment by kaplanelad** [comment]
Hey @kpetreman, thanks for reporting this issue.
Do you want to open a pull request with your fix? We're accepting PRs

**Comment by kpetremann** [comment]
sure, I'll add it and then send the PR!

**Comment by kpetremann** [comment]
@kaplanelad I added the e2e test in the PR #132, don't hesitate if it needs adjustments

**Comment by kpetremann** [comment]
closing the issue as the PR has been merged and released.

Thanks for having merge the PR :)
