### ISSUE TITLE
localstack compatibility for aws providers

### ISSUE THREAD

**Issue by JacobJohansen** [tellerops/teller#134]
## Feature Request
Allow teller to be pointed at localstack for aws_secretsmanager and aws_ssm providers

**Is your feature request related to a problem? Please describe.**

provide a method to override the default aws endpoint to allow local developers to use the same process as our deployments
 
**Describe the solution you'd like**

use the AWS_ENDPOINT environment variable to allow for a custom endpoint to be used with localstack
**Describe alternatives you've considered**

Provider configuration value

**Comment by kaplanelad** [comment]
Thanks @JacobJohansen. new version released with your PR: 1.5.6
