### ISSUE TITLE
AWS SSM (parameter store) sync by path

### ISSUE THREAD

**Issue by david-heward-unmind** [tellerops/teller#148]
## Feature Request

Correct me if I am wrong, but it would appear that it is currently not possible to sync from AWS SSM parameter store based on the path. Is this on the roadmap? Often its useful to take a path and translate parameters under these paths to env variables. Could we get this on the roadmap?

I specifically meaning syncing all parameters recursively below a path i.e. using `aws ssm get-parameters-by-path` and setting those to appropriately named env vars? i.e. uppercase, underscores, etc

I guess it would mean implementing `sync` 
https://github.com/tellerops/teller/blob/bdea7e096c4319a27d5a26187f08bfac8fe32f76/pkg/providers/aws_ssm.go#L77

**Comment by jondot** [comment]
yes it is, happy to jump on a zoom session with you some time next week, and learn about your use case. would that make sense for you?

**Comment by david-heward-unmind** [comment]
@jondot I am not sure that would be required in this instance. To me it's a fairly simple issue to overcome, we are talking here about simply adding the ability for AWS SSM parameter store parameters to be looked up by partial path. i.e. `/dev/` which would translate anything discovered by the final segment of the `/dev/var1` `/dev/platform/var2` etc into env vars.

I believe you are calling this feature `sync`

**Comment by jondot** [comment]
should be resolved now via Teller 2.0 reimplementation of AWS SSM, thanks!
