### ISSUE TITLE
Support for Scoop (windows installer) 

### ISSUE THREAD

**Issue by MrLuje** [tellerops/teller#152]
## Feature Request

**Is your feature request related to a problem? Please describe.**
On linux/mac, you can use homebrew to install Teller but on Windows, you are currently limited to a manual install through the release page.

**Describe the solution you'd like**
Support for [Scoop](https://github.com/ScoopInstaller/Scoop) which is a command-line installer which also supports automated updates. Apart for breaking changes in the release process (assets filename changes, etc), this should be a completly automated process on Scoop's side to handle new versions.

TODO:
- [ ] Declare Teller in [Scoop main bucket](https://github.com/ScoopInstaller/Main) (this will roughtly looks like [k9s's definition](https://github.com/ScoopInstaller/Main/blob/master/bucket/k9s.json))
- [ ] Update Teller docs to include the command to install it through Scoop

If that's ok for you, I can work on both tasks

Thanks

**Comment by jondot** [comment]
Thanks, as we've moved to Teller 2.0, we'd be happy to see something like this.
I'll be closing but please reopen if still relevant
