### ISSUE TITLE
Fury releases (rpm, deb, apt) 

### ISSUE THREAD

**Issue by mrsufgi** [tellerops/teller#156]
## Feature Request
As far as I know, GoReleaser can use Fury, snapcraft etc for releasing for apt, apk, rpm, yum etc. 

**Is your feature request related to a problem? Please describe.**
Please add this minor release channel to simplify installing inside a docker, linux envs etc. 

**Describe the solution you'd like**
Installing from git releases is not sustainable.

**Comment by polarathene** [comment]
Caddy project does this with a Github Actions release workflow:
- [Example for publishing to GemFury](https://github.com/caddyserver/caddy/blob/b7e472d54884de4ecd6147784c74fb448180e9d1/.github/workflows/release.yml#L118-L135).
- [Example for publishing to CloudSmith](https://github.com/caddyserver/caddy/blob/b7e472d54884de4ecd6147784c74fb448180e9d1/.github/workflows/release.yml#L155-L174).

Caddy is [also leveraging GoReleaser](https://github.com/caddyserver/caddy/blob/b7e472d54884de4ecd6147784c74fb448180e9d1/.github/workflows/release.yml#L89-L116) as part of that workflow. Should be a good reference if this project wants to improve their release strategy 😁

**Comment by jondot** [comment]
Thanks, we have moved to Rust, we will happily accept a PR that can help package to various native package formats.
Closing this for now, thanks again!
