### ISSUE TITLE
Support `.yaml` file extension

### ISSUE THREAD

**Issue by prochac** [tellerops/teller#162]
## Feature Request

Add support for `.teller.yaml` file. 

**Is your feature request related to a problem? Please describe.**

Official file extension for YAML files is `.yaml`
https://yaml.org/faq.html

We no longer live in [the era of 3 chars limit for file extensions](https://en.wikipedia.org/wiki/8.3_filename).
Even Microsoft doesn't have problem to use `.xlsx` etc. for modern systems.

**Describe the solution you'd like**

Try `.yml` first, for backward compatibility, then try `.yaml`

Related discussion here about extension for GitLab CI pipeline runner.
https://gitlab.com/gitlab-org/gitlab/-/issues/26169

**Comment by kaplanelad** [comment]
Hi @prochac,
thank you for opening the issue on our open source project. Your contribution is greatly appreciated!

If you're interested, would you consider opening a pull request with your suggested solution? 
We here to help you if you needs

**Comment by prochac** [comment]
Cool, if you're open to this idea, I can give a look, that's sure.

**Comment by kaplanelad** [comment]
@prochac let me know if you need my help.
thanks

**Comment by prochac** [comment]
> @prochac let me know if you need my help. thanks

Thanks for a ping :) Can I ask you for a review? :)

**Comment by kaplanelad** [comment]
@prochac i saw that @jondot already did.

thank you !
