### ISSUE TITLE
New AWS SSO Config Format Breaks teller

### ISSUE THREAD

**Issue by stvnksslr** [tellerops/teller#177]
## Expected Behavior
Teller should handle both the legacy and new aws cli sso formats

## Current Behavior
you need to setup your sso with the legacy format in order to use teller

## Steps to Reproduce
 
1. aws configure sso
2. when prompted for a sso session name use one, if you do not enter a name here it will revert to the legacy format.
3. attempt to fetch secrets via teller ex. teller env
4. receive error that your sso config is missing values / invalid

error from teller
```
FATA[0000] could not load all variables from the given existing providers  error="profile \"default\" is configured to use SSO but is missing required configuration: sso_region, sso_start_url"
```

**Comment by kemosabe102** [comment]
It seems that `sso_session` is not supported. The new [AWS SSO auto-token refresh method](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html#sso-configure-profile-token-manual) includes that field in the `config` file. After removing that line from my config file, `teller env` started working.

I always received this type of error:
```
FATA[0000] could not load all variables from the given existing providers  error="operation error Secrets Manager: GetSecretValue, failed to sign request: failed to retrieve credentials: the SSO session has expired or is invalid: open /Users/username/.aws/sso/cache/b1464194774a2651eaf92e19bda80332517c6b57.json: no such file or directory"
```
When I check `/Users/username/.aws/sso/cache/`, that json file doesn't exist, but the most recent one that I got from running `aws sso login` was there.

**Comment by stvnksslr** [comment]
No longer an issue in 2.0
