### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by polarathene** [tellerops/teller#181]
Last release was Oct 2022 (`1.5.6`), there's been a few additions/fixes since (_and we're almost at 12 months since a release was made_): https://github.com/tellerops/teller/commits/master

Notably:
- Fix for redaction process a stream immediately instead of blocking until child process ends.
- `remap_with` option.
- `.teller.yml` fallback.

Perhaps a `1.6.0` could be tagged and released, or is there a blocker?

---

Related:
- Possible release improvement via packaging?: https://github.com/tellerops/teller/issues/156
- CI workflows update to benefit the next tagged release: https://github.com/tellerops/teller/pull/180

**Comment by jondot** [comment]
closing in favor of upcoming teller 2.0
