### ISSUE TITLE
Integrate Teller with Popular Windows Package Managers

### ISSUE THREAD

**Issue by Amoenus** [tellerops/teller#190]
### **Is your feature request related to a problem? Please describe.**  

While the current manual installation process for Teller on Windows is functional, incorporating package managers like Chocolatey and winget could offer users a more seamless and integrated experience.

### **Describe the solution you'd like**  

I would like to request the inclusion of a Chocolatey, winget, and Scoop package for Teller. This would allow users to easily install and update Teller using simple commands such as:

**Chocolatey:**
- Installation: `choco install teller`
- Update: `choco upgrade teller`

**winget:**
- Installation: `winget install tellerops.teller`
- Update: `winget upgrade tellerops.teller`

**Scoop:**
- Installation: `scoop install teller`
- Update: `scoop update teller`

Offering these installation methods not only provides a smoother experience for users but also ensures that they always have access to the latest stable version.

### **Describe alternatives you've considered**  

**Manual Installation**: While manual installation works, it's not as streamlined or convenient as using a package manager. This method also doesn't provide automatic updates.

**Comment by jondot** [comment]
Thanks for this request -- i would love for this to come from contribution, as I'm no longer a Windows expert. Closing this for now, but if you want to submit a PR we'd happily look at it.
