### ISSUE TITLE
Github action fails to install with error: repository not found

### ISSUE THREAD

**Issue by nikolasten** [tellerops/teller#192]
## Expected Behavior
Install gh action successfully

## Current Behavior
Fails

## Steps to Reproduce
Add 
```yaml
name: Setup Teller
uses: spectralops/setup-teller@v1
```
or

```yaml
name: Setup Teller
uses: spectralops/setup-teller@v2
```
in `jobs.build.steps`

**Comment by philippeckelintive** [comment]
@nikolasten the documentation is unfortunately wrong; please see [my PR](https://github.com/SpectralOps/setup-teller-action/pull/3/files) which covers the right action name.

**Comment by nikolasten** [comment]
Thanks! Closing this in favour of your issue and pr
