### ISSUE TITLE
etcd provider does not work as expected

### ISSUE THREAD

**Issue by bamoo456** [tellerops/teller#193]
## Expected Behavior
Based on the [README.md](https://github.com/tellerops/teller#authentication-3), the following execution should work.
```
ETCDCTL_ENDPOINTS=x.x.x.x:2379 ETCDCTL_USER=read ETCDCTL_PASSWORD teller show
```

## Current Behavior
The above command gave me:
```
FATA[0000] could not load all variables from the given existing providers  error="etcdserver: user name is empty"
```

## Possible Solution
I would suggest explicitly add a username and password while instantiating a `etcd` client, for example:
Update the [code](https://github.com/tellerops/teller/blob/281252f6865156aa52ad335719aa178715e53ae7/pkg/providers/etcd.go#L146) to be following: 
```
	cfg := clientv3.Config{
		TLS:       tr,
		Endpoints: eps,
		Username:  os.Getenv("ETCDCTL_USER"),
		Password:  os.Getenv("ETCDCTL_PASSWORD"),
	}
```

## Steps to Reproduce

1. Dowload the latest release version `1.5.6`.
2. Execute the `teller` by: `ETCDCTL_ENDPOINTS=x.x.x.x:2379 ETCDCTL_USER=read ETCDCTL_PASSWORD teller show`
3. You should see the unexpected errors.

## Context
The issue is the `etcd` provider was not work as expected, so we need a fix for people using `etcd`.

## Specifications
  - Version: 
  ```
  Teller 1.5.6
  Revision 7b714bc2f1d5e14920f2add828fdf7425148ff6b, date: 2022-10-13T08:02:44Z
```
  - Platform: `Ubuntu 22.04`

**Comment by jondot** [comment]
we have a new etcd provider as part of the Teller 2.0 rewrite, please reopen if issue persists.
