### ISSUE TITLE
README - Product Hunt link badge is broken and listing is marked for removal

### ISSUE THREAD

**Issue by mkol5222** [tellerops/teller#196]
## Expected Behavior
[README.md](https://github.com/tellerops/teller#readme ) icon for Product Hunt [link](https://www.producthunt.com/posts/teller-3?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-teller-3) should have expected badge/icon.
When [Product Hunt link to Teller](https://www.producthunt.com/posts/teller-3?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-teller-3) is clicked, 
one should not get warning/error page that Product Hunt listing is marked for removal.

## Current Behavior
Broken badge on Product Hunt link and not getting straight to Teller's Product Hunt page without error message on their side.
![image](https://github.com/tellerops/teller/assets/229723/6ffaaa2a-25d9-4037-809d-64863df547f6)

## Steps to Reproduce
1. Look at https://github.com/tellerops/teller#readme - icon for Product Hunt is loaded broken
2. Click Product Hunt link - you get warning that listing is marked for removal instead of real listing

## Notes
It is small cosmetic issue, but we should be aiming for perfection.
Target page error message below:
![image](https://github.com/tellerops/teller/assets/229723/7e7bd55f-08e9-4baa-a4a5-e067ba277011)

**Comment by jondot** [comment]
taken care of with teller 2.0 readme.
