### ISSUE TITLE
Devstats showing inactive?

### ISSUE THREAD

**Issue by amye** [tellerops/teller#204]
Checking in here, Devstats is showing your project as inactive in the past 90 days.
(https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1 )

If this is an error, we can help get you updated!
If it's accurate, can we help? The Technical Oversight Committee is beginning to review inactive projects, and we want to make sure that we're getting good data for them.

Please make sure that you update your developer affiliation data accurately via https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation and openprofile.dev - so we have an accurate representation of what organizations are contributing to CNCF projects. You may also want to update maintainers.cncf.io to reflect the latest list of maintainers for your projects. 

Let us know how we can help!

**Comment by amye** [comment]
Wonderful - let's get a pull request back into devstats to resolve this: 
https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1 shows 113 days since your last commit. 
<img width="108" alt="Projects_Health_Table_-_Grafana" src="https://github.com/tellerops/teller/assets/107161/4485111f-197e-4255-9901-dad8340f4260">

**Comment by jondot** [comment]
closing this towards teller 2.0
