### ISSUE TITLE
Fix redact for environment ( or perhaps other provider ) variables that expand to empty string

### ISSUE THREAD

**Issue by darach** [tellerops/teller#217]
## Expected Behavior

Given a configuration that users the .env provider with a configuration containing any
variable that mapss to the empty string

```shell
FOO=""
```

Redaction should ignore the variable.

## Current Behavior

```shell
$ cat test.txt
This is a test
$ cat test.txt| teller redact
**REDACTED**T**REDACTED**h**REDACTED**i**REDACTED**s**REDACTED** **REDACTED**i**REDACTED**s**REDACTED** **REDACTED**a**REDACTED** **REDACTED**t**REDACTED**e**REDACTED**s**REDACTED**t**REDACTED**
```

## Possible Solution

Preprocess and remove variables that expand to the empty string.

## Steps to Reproduce

1. Create a `.teller.yml` with an env provider as above
2. Create a non empty `test.txt` file as above
3. Redact the file with teller
4. Every character will contain an unwanted `**REDACTED**` 

## Context

Ideally, environment variables should not expand to the empty string - but this will not always be practicable or possible

## Specifications
  - Version: `$ teller version`
  ```
  Teller 1.5.6
Revision 7b714bc2f1d5e14920f2add828fdf7425148ff6b, date: 2022-10-13T08:02:44Z
```
  - Platform:
  ```
   uname -a | teller redact
Darwin **REDACTED** 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:26 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_X86_64 x86_64
```

**Comment by jondot** [comment]
Thanks, should be fixed with Teller 2.0 now.
