### ISSUE TITLE
invalid map value: "-A"

### ISSUE THREAD

**Issue by ilja-ag** [tellerops/teller#233]
## Expected Behavior

teller put should accept any string, i.e. teller put A="-A"

## Current Behavior

teller: error: <kvs> ...: invalid map value "-A"

## Steps to Reproduce

I have used AWS SM provider, but something tells me it is generic teller put problem

## Context

Secret value starts with '-'

## Specifications
  - Version: `$ teller version`
Teller 1.5.6
Revision 7b714bc2f1d5e14920f2add828fdf7425148ff6b, date: 2022-10-13T08:02:44Z
  - Platform: 
x86_64 i386 Darwin

**Comment by jondot** [comment]
thanks, fixed as part of Teller 2.0
