### ISSUE TITLE
`teller env` produces unquoted variable values that have whitespace characters

### ISSUE THREAD

**Issue by zshehov** [tellerops/teller#240]
## Expected Behavior
Variables containing whitespace characters should be quoted on `env` generation

## Current Behavior
Variables containing whitespace characters are produced without quotes in the resulting env file after `teller env`. Also, variables coming from a dotenv provider that already have quotes have their quotes removed.

## Possible Solution
Persist already quoted variable values in the dotenv provider + Scan for whitespaces and quote values for `teller env` output

## Steps to Reproduce
1. Create a source dotenv .env.source file with a variable including whitespace: TEST="two words"
2. Create a .teller.yml file with dotenv provider that has 
```
env_sync:
      path: .env.source
```
4. Call `teller env`
5. The produced output has TEST=two words

## Specifications
  - Version:
Teller 1.5.6
Revision 7b714bc2f1d5e14920f2add828fdf7425148ff6b, date: 2022-10-13T08:02:44Z
  - Platform: MacOS arm64

**Comment by jondot** [comment]
Thanks, should be fixed with Teller 2.0 now
