### ISSUE TITLE
tlr.dev registration is expired

### ISSUE THREAD

**Issue by punasusi** [tellerops/teller#251]
## Expected Behavior
website linked in README to be active

## Current Behavior
Namecheap offers me to renew

## Possible Solution
renew the domain, or remove the link

## Steps to Reproduce
1. open repo page in GitHub 
2. click the link to project
3. be disappointed 

## Context
Maybe all the docs can be found in GitHub readme files, but having a website linked that doesn't work feels like project is abandoned (and I really hope that's not the case)

**Comment by jondot** [comment]
Thanks, we're removing this domain as it's not bringing any value any more.

**Comment by pgpx** [comment]
Could the link to tlr.dev on <https://www.cncf.io/projects/teller/>  be updated?

**Comment by prochac** [comment]
The domain is available to anybody now, allowing domain squatting.

The domain is linked from CNCF for example.
This is not a very responsible behavior from a security tool.

https://www.cncf.io/projects/teller/

![Screenshot_20240602_021050](https://github.com/tellerops/teller/assets/20124774/b6b09503-373e-4622-af27-f1fde9c33570)

**Comment by prochac** [comment]
The domain is available to anybody now, allowing domain squatting.

The domain is linked from CNCF for example.
This is not a very responsible behavior from a security tool.

https://www.cncf.io/projects/teller/

![Screenshot_20240602_021329](https://github.com/tellerops/teller/assets/20124774/76f08749-4a5a-47ef-86a7-36a8b93d16d2)
