### ISSUE TITLE
missing version command with teller v2

### ISSUE THREAD

**Issue by chenrui333** [tellerops/teller#272]
👋 while [upgrading teller homebrew formula to v2](https://github.com/Homebrew/homebrew-core/pull/171501), I found there is no `version` command anymore, is that desired? Thanks!

**Comment by jondot** [comment]
hello! adding this right now, thanks for the catch!

**Comment by jondot** [comment]
https://github.com/tellerops/teller/releases/tag/v2.0.4

should be good there: `teller --version`

**Comment by chenrui333** [comment]
close via https://github.com/Homebrew/homebrew-core/pull/171517
