### ISSUE TITLE
build a docs website w/docusaurus

### ISSUE THREAD

**Issue by jondot** [tellerops/teller#64]
Time for shaping the content. Build a docs website based on the following TOC:

* Quickstart
* Providers (let's also do something smart. Each provider should also specify declaratively what it supports, so when we run something like "teller providers --info" we get a JSON that we can bake into the docs). In other words - we want the providers to be self-documenting so that:
1. maintainers can contribute very easily
2. syncing the docs provider section is effortless or automatic
* Usage (list all use cases)
* FAQ
* Design principles
* Contributing (developer's guide)

**Comment by abtris** [comment]
Hi, 
 any plans about it create docs?

I find hard to start with Azure provider. I resolve after a few attempts but some quick start and tutorial will be useful and plus some provider list and specific problems. 

I'm happy to kick off something if make it sense for you. 

L.

**Comment by tehret77** [comment]
Hi @abtris 
can you write down which what you had to configure?
I don't understand right now what else needs to be configured for authentication.
Thanks!

**Comment by dirathea** [comment]
Hello there!

First of all, I think this tools is great and have great potential of it. To help folks starts using Teller, I agree to create website for documents itself. I read the README.md and it has plenty useful information on it. Put those information to docusaurus will be very useful.

To do that, I've initiate the docusaurus creation and deploy it on my own repo first. Check this out https://dirathea.github.io/teller/ and tell me what you think 😄. If this works out, maybe we can talk about bring this documentations to the upstream repository.
