### ISSUE TITLE
Add bitwarden provider

### ISSUE THREAD

**Issue by kaplanelad** [tellerops/teller#79]
## New Provider Request
Add [bitwarden](https://bitwarden.com/) provider

## Details
- Name: bitwarden
- URL: https://bitwarden.com/
- Modes: (read/write/read+write)
- GitHub projects: 
- API Documentation:  https://bitwarden.com/help/public-api/, https://bitwarden.com/help/api/

**Comment by Vad1mo** [comment]
This would be outstanding to use in combination with https://github.com/dani-garcia/vaultwarden

**Comment by dstengle** [comment]
Disappointing to see this closed. I guess this is not a priority? I recently switched from lastpass to bitwarden and I've been pretty happy so far.

**Comment by kaplanelad** [comment]
Hello @dstengle, at the moment, we do not have any immediate plans to integrate the bitwarden provider. However, we highly appreciate and encourage contributions from the community if you are interested.

I am available to assist you with anything you may need.
