### ISSUE TITLE
Inspecting specific variables 

### ISSUE THREAD

**Issue by ChengaDev** [tellerops/teller#91]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Today when inspecting variables using the `show` command, it outputs all the entries from all the providers.
There is no way to inspect/focus a single provider or a single entry.

![image](https://user-images.githubusercontent.com/44297242/163704801-18106b04-722e-41c2-9d46-20075f801843.png)

**I'd suggest to:**
1. Enable looking for single / more specific entries by key param to `show` command.
2. Enable looking for entries of a specific provider.

**Describe the solution you'd like**
1. Group the results of `show` by the provider.
2. New 2 optional parameters to show command:
- `--entry` - for searching specific entry value / pattern using `contains` or regular expression.
- `--providers` - list of providers to show their entries in the `show` command.

**Comment by kaplanelad** [comment]
@ChengaDev this issue still relevant? 
can we close it?
